In [226]:
import numpy as np

Shapes of different matrices
* Ai -- activations from a layer (layers_dims[i], num_examples)
* Wi -- weight matrix of shape (layers_dims[i], layers_dims[i-1])
* bi -- bias vector of shape (layers_dims[i], 1)
* X -- input data, numpy array of shape (input size, number of examples)

### Initialization

In [227]:
def initialize_parameters(layer_dims, init_type='random'):
    """
    Performs a given initialization for the weight matrices and zero initialization for biases.
    layer_dims -- list with the dimensions of each layer in our network
    init_type: either 'random', 'he', 'xavier'
    Returns:
    parameters -- dictionary with parameters
    """
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):
        if init_type == 'random':
            scaling_factor = 0.01
        elif init_type == 'he':
            scaling_factor = np.sqrt(2.0 / layer_dims[l-1])
        elif init_type == 'xavier':
            scaling_factor = np.sqrt(1.0 / layer_dims[l-1])
        else:
            raise Error("Initialization type " + init_type + " not supported")
    
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * scaling_factor
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

    return parameters

In [228]:
def random_initialization(layer_dims):
    """
    Performs random initialization with a scaling factor 0.01
    """
    return initialize_parameters(layer_dims, init_type='random')

In [229]:
def xavier_initialization(layer_dims):
    """
    Performs Xavier initialization with a scaling factor sqrt(1/prev_layer_dimension)
    """
    return initialize_parameters(layer_dims, init_type='xavier')

In [230]:
def he_initialization(layer_dims):
    """
    Performs He initialization with a scaling factor sqrt(2/prev_layer_dimension)
    """  
    return initialize_parameters(layer_dims, init_type='he')

### Regularization

In [234]:
def get_L2_regularization_cost(parameters, lambd):
    """
    Return L2 regularization term.
    
    Arguments:
    parameters -- python dictionary containing parameters of the model
    lambd -- regularization hyperparameter, scalar

    Returns:
    cost - value of the regularization term to be used for cost function regularization
    """
    m = Y.shape[1]
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    W3 = parameters["W3"]

    sum_of_squares = np.sum(np.square(W1) + np.sum(np.square(W2)) + np.sum(np.square(W3)))
    L2_regularization_cost = 1/m * lambd/2 * sum_of_squares
    
    return L2_regularization_cost

### Mini-batch

In [235]:
def shuffle(vec, num_examples):
    if len(vec) == 0:
        return vec
    permutation = list(np.random.permutation(num_examples))
    return vec[:, permutation]

In [236]:
def random_mini_batches(X, Y, mini_batch_size = 64, seed = 0):
    """
    Creates a list of random minibatches from (X, Y)
    
    Arguments:
    X -- input data, shape (input size, number of examples)
    Y -- ground thruth vector, shape (1, number of examples)
    mini_batch_size -- size of the mini-batches, integer
    
    Returns:
    mini_batches -- list of (mini_batch_X, mini_batch_Y)
    """
    
    np.random.seed(seed)
    m = X.shape[1]
    mini_batches = []
        
    shuffled_X = shuffle(X)
    shuffled_Y = shuffle(Y).reshape((1,m))

    num_complete_minibatches = math.floor(m/mini_batch_size) # number of mini batches of size mini_batch_size in your partitionning
    for k in range(0, num_complete_minibatches):
        mini_batch_X = shuffled_X[:, k * mini_batch_size : (k+1) * mini_batch_size]
        mini_batch_Y = shuffled_Y[:, k * mini_batch_size : (k+1) * mini_batch_size]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)
    
    # Handling the end case (last mini-batch < mini_batch_size)
    if m % mini_batch_size != 0:
        num_remaining_examples = m - mini_batch_size * np.floor(m / mini_batch_size)
        last_example_index = num_complete_minibatches * mini_batch_size + num_remaining_examples
        mini_batch_X = shuffled_X[:, num_complete_minibatches * mini_batch_size : last_example_index]
        mini_batch_Y = shuffled_Y[:, num_complete_minibatches * mini_batch_size : last_example_index]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)
    
    return mini_batches


### Optimization algorithms

In [237]:
def relu(z):
    x = np.array(z, copy=True)
    np.maximum(x, 0, x) # modifies x in place
    return (x, z)

In [239]:
def sigmoid(z):
    return  (1.0 / (1 + np.exp(-z)), z)

In [ ]:
def sigmoid_backward(dA, cache):
    x = cache # cached sigmoid of Z
    dZ = dA * (x * (1 - dA))
    return dZ

In [263]:
def relu_backward(dA, cache):
    dZ, x = None, cache
    dZ = np.array(dA, copy=True)
    dZ[ x <= 0 ] = 0
    return dZ

In [241]:
def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation with a linear step and an activation step, for one layer

    Arguments:
    A_prev -- activations from previous layer (or input data)
    W -- weights matrix
    b -- bias vector
    activation -- the activation to be used in this layer: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function (post-activation value)
    cache -- a python dictionary containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    # Linear step
    Z = np.dot(W, A_prev) + b
    linear_cache = (A_prev, W, b)
    
    # Activation step
    if activation == "sigmoid":
        A, activation_cache = sigmoid(Z)
    elif activation == "relu":
        A, activation_cache = relu(Z)
    else:
        raise Error("Activation function " + activation + " is not supported.")
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)

    return A, cache

In [243]:
def forward_propagation(X, parameters):
    """
    Implement forward propagation for the relu (hidden layers) and sigmoid (output layer) computation
    
    Arguments:
    X -- data
    parameters -- output of initialize_parameters()
    
    Returns:
    AL -- last post-activation value
    caches -- list of caches output of linear_activation_forward() 
    """

    caches = []
    A = X
    L = len(parameters) // 2 # of layers in the network
    
    for l in range(1, L):
        A_prev = A
        A, cache = linear_activation_forward(A_prev, parameters["W"+str(l + 1)], parameters["b"+str(l + 1)], "relu")
        caches.append(cache)

    A_last, cache = linear_activation_forward(A, parameters["W"+str(L)], parameters["b"+str(L)], "sigmoid")
    caches.append(cache)

    assert(A_last.shape == (1,X.shape[1]))
            
    return A_last, caches

In [245]:
def linear_backward(dZ, cache):
    """
    Implement the linear portion of backward propagation for a single layer

    Arguments:
    dZ -- Gradient of the cost with respect to the linear output
    cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer

    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    A_prev, W, b = cache
    m = A_prev.shape[1]

    dW = 1/m * np.dot(dZ, A_prev.T)
    db = 1/m * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T, dZ)
    
    assert (dA_prev.shape == A_prev.shape)
    assert (dW.shape == W.shape)
    assert (db.shape == b.shape)
    
    return dA_prev, dW, db

In [246]:
def linear_activation_backward(dA, cache, activation):
    """
    Implement the backward propagation for the LINEAR->ACTIVATION layer.
    
    Arguments:
    dA -- post-activation gradient for current layer l 
    cache -- tuple of values (linear_cache, activation_cache) stored for computing backward propagation efficiently
    activation -- the activation to be used in this layer, "sigmoid" or "relu"
    
    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    linear_cache, activation_cache = cache
    
    if activation == "relu":
        dZ = relu_backward(dA, activation_cache)
    elif activation == "sigmoid":
        dZ = sigmoid_backward(dA, activation_cache)
    else:
        raise Error("Activation function " + activation + " is not supported.")      
    
    dA_prev, dW, db = linear_backward(dZ, linear_cache)

    return dA_prev, dW, db

In [252]:
def backward_propagation(A_last, Y, caches):
    """
    Implement the backward propagation for the [LINEAR->RELU] * (L-1) -> LINEAR -> SIGMOID group
    
    Arguments:
    A_last -- probability vector, output of the forward propagation
    Y --  the ground truth vector 
    caches -- list of caches containing:
                the caches of linear_activation_forward() with "relu" and 
                the cache of linear_activation_forward() with "sigmoid"
    
    Returns:
    grads -- A dictionary with the gradients for each layer
    """
    grads = {}
    L = len(caches)
    m = A_last.shape[1]
    Y = Y.reshape(A_last.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    dAL = - (np.divide(Y, A_last) - np.divide(1 - Y, 1 - A_last))
    
    # Lth layer gradients.
    current_cache = caches[L-1]
    grads["dA" + str(L)], grads["dW" + str(L)], grads["db" + str(L)] = \
        linear_activation_backward(dAL, current_cache, "sigmoid")
    
    for l in reversed(range(L-1)):
        j = str(l + 1)
        # lth layer gradients.
        current_cache = caches[l]
        grads["dA" + j], grads["dW" + j], grads["db" + j] = \
            linear_activation_backward(grads["dA" + str(L)], current_cache, "relu")

    return grads

### Cost calculation

In [248]:
def compute_cost(A_last, Y):
    """
    Implement the cost function with L2 regularization. See formula (2) above.
    
    Arguments:
    A_last -- post-activation, output of forward propagation, of shape (output size, number of examples)
    Y -- "true" labels vector, of shape (output size, number of examples)
    
    Returns:
    cost - value of the loss function
    """
    m = Y.shape[1]
    logprobs = np.multiply(np.log(A_last), Y) + np.multiply(np.log(1 - A_last), 1 - Y)
    cost = - 1.0 / m * np.sum(logprobs)
    
    cost = np.squeeze(cost)
    return cost

### Parameter update

In [250]:
def update_parameters(parameters, grads, learning_rate):
    """
    Update parameters using gradient descent
    """
    L = len(parameters) // 2 # number of layers in the neural network

    for l in range(L):
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)] 
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
        
    return parameters

### Neural network model

In [251]:
def nn_model(X, Y, n_h, layers_dims, learning_rate=0.0075, num_iterations=1000, mini_batch_size=64,
             seed=0, print_cost=False):
    """
    Implements a neural network with relu activation function for the hidden layers and
    a sigmoid actication function for the output layer.
    """
    np.random.seed(1)
    costs = []

    parameters = initialize_parameters(layers_dims, init_type='random')

    for i in range(0, num_iterations):
        A_last, caches = forward_propagation(X, parameters)
        cost = compute_cost(A_last, Y)
        grads = backward_propagation(A_last, Y, caches)
        parameters = update_parameters(parameters, grads, learning_rate)
                
        # Print cost
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
            costs.append(cost)

    # plot the cost
    plt.plot(np.squeeze(costs))
    plt.ylabel('cost')
    plt.xlabel('iterations (per tens)')
    plt.title("Learning rate =" + str(learning_rate))
    plt.show()
    
    return parameters

In [ ]:
def predict(train_x, train_y, parameters):
    pass
    return Y_prediction

### Tests

In [253]:
# Test initialize params
parameters = initialize_parameters([2, 4, 1], init_type='he')
assert(parameters["W1"][0][0] - 1.78862847 < 10e-8)
assert(parameters["W1"][0][1] - 0.43650985 < 10e-8)
assert(parameters["b1"][0][0] - 0.0 < 10e-8)
assert(parameters["W2"][0][0] + 0.00043818 < 10e-8)
assert(parameters["b2"][0][0] - 0.0 < 10e-8)

In [254]:
# Test initialize params
parameters = initialize_parameters([2, 4, 1], init_type='xavier')
assert(parameters["W1"][0][0] - 1.78862847 < 10e-8)
assert(parameters["W1"][0][1] - 0.43650985 < 10e-8)
assert(parameters["b1"][0][0] - 0.0 < 10e-8)
assert(parameters["W2"][0][0] + 0.021909084488 < 10e-8)
assert(parameters["b2"][0][0] - 0.0 < 10e-8)

In [255]:
# Test initialize params
parameters = initialize_parameters([2, 4, 1])
assert(parameters["W1"][0][0] - 1.78862847 < 10e-8)
assert(parameters["W1"][0][1] - 0.43650985 < 10e-8)
assert(parameters["b1"][0][0] - 0.0 < 10e-8)
assert(parameters["W2"][0][0] - (-0.00043818) < 10e-8)
assert(parameters["b2"][0][0] - 0.0 < 10e-8)

In [256]:
# Test relu
print ("relu([0, 2]) = " + str(relu(np.array([0,2]))))

relu([0, 2]) = (array([0, 2]), array([0, 2]))


In [257]:
# Test sigmoid
print("sigmoid([0, 2]) = " + str(sigmoid(np.array([0,2]))))
print("exptected: [ 0.5 0.88079708]") 

sigmoid([0, 2]) = (array([ 0.5       ,  0.88079708]), array([0, 2]))
exptected: [ 0.5 0.88079708]


In [258]:
# Test linear_activation_forward
A_prev = np.array([[ 4.,  7.,  3.], [ 2.,  0.,  5.]])
W = np.array([[ 2.,  4.], [ 1.,  1.], [ 3.,  3.], [ 2.,  2.]])
b = np.array([[ 1.], [ 2.], [ 3.], [ 4.]])

A, _ = linear_activation_forward(A_prev, W, b, 'sigmoid')
A_expected = np.array(
[[ 0.99999996,  0.99999969,  1.        ],
 [ 0.99966465,  0.99987661,  0.9999546 ],
 [ 1.,          1.,          1.        ],
 [ 0.99999989,  0.99999998,  1.        ]])

print(A)

A, _ = linear_activation_forward(A_prev, W, b, 'relu')
A_expected = np.array(
[[ 17.,  15.,  27.],
 [  8.,   9.,  10.],
 [ 21.,  24.,  27.],
 [ 16.,  18.,  20.]])

print(A)

[[ 0.99999996  0.99999969  1.        ]
 [ 0.99966465  0.99987661  0.9999546 ]
 [ 1.          1.          1.        ]
 [ 0.99999989  0.99999998  1.        ]]
[[ 17.  15.  27.]
 [  8.   9.  10.]
 [ 21.  24.  27.]
 [ 16.  18.  20.]]


In [259]:
# Test forward_propagation
X = np.array([[ 4.,  7.], [ 2.,  0.]])
parameters = initialize_parameters([2, 1])

A_last, caches = forward_propagation(X, parameters)
print("A_last = " + str(A_last))
print("Length of caches list = " + str(len(caches)))

print("expected A_last: [[ 0.52005806  0.53126017]]")
print("expected caches list len: 1")

A_last = [[ 0.52005806  0.53126017]]
Length of caches list = 1
expected A_last: [[ 0.52005806  0.53126017]]
expected caches list len: 1


In [260]:
# Test backward_propagation
X = np.array([[ 4.,  7.], [ 2.,  0.]])
parameters = initialize_parameters([2, 1])

A_last, caches = backward_propagation(X, parameters)
print("A_last = " + str(A_last))
print("Length of caches list = " + str(len(caches)))

print("expected A_last: [[ 0.52005806  0.53126017]]")
print("expected caches list len: 1")

TypeError: backward_propagation() takes exactly 3 arguments (2 given)

In [262]:
# Test compute_cost
A_last = np.array([[0.40682402, 0.01629284, 0.16722898, 0.10118111, 0.40682402]])
Y = np.array([[1, 1, 0, 1, 0]])

assert(compute_cost(A_last, Y) - 1.60250160476 < 10e-5)